///<reference types="cypress-xpath" />
import info from '../../fixtures/bookADemoData.json'
import info1 from '../../fixtures/debtorhelpdeskconnetdata.json'

var today = new Date();
var monthnumber = today.getMonth() + 1;
var yearnumber = today.getFullYear();


class YearData {
    get yearname() {
        return "28 October 2021"
    }
}
var yr = new YearData();
var Dates = yr.yearname;
//selecting dates 1 or 2 digit
var datevalue = Dates.substring(0, 2)
if (Dates.substring(0, 2) < "10") {
    datevalue = Dates.substring(1, 2);
}
var monthvar = Dates.substring(3, Dates.length - 5);
var yearvar = Dates.substring(Dates.length - 4, Dates.length)
console.log(monthvar);
console.log(yearvar);
var months = [
    "January",
    "Februry",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
];

var mon = 0;
for (let i = 0; i < months.length; i++) {
    var x = months[i];
    console.log(x);
    if (months[i] == monthvar) {
        mon = i;
    }
}

var yeardata = yearvar - yearnumber;
var monthtimes = mon - monthnumber + 1;
var buttonpress = monthtimes + (yeardata * 12)
console.log(buttonpress)

class DebtorDashboard {
    verifyTitleandUrl() {
        cy.xpath('//span[text()="My Dashboard"]').should('have.text', 'My Dashboard')
        cy.url().should('eq', 'http://cva-india-test.s3-website.ap-south-1.amazonaws.com/dashboard/debtor')
    }
    verifyCompanyName() {
        cy.get('#company-name').should('exist')
    }
    verifyTexts() {
        cy.get('#debtor-industry').should('exist')//industry type
        cy.get('.left_wrap > ul > :nth-child(2)').should('exist')//debtor type
        cy.xpath('//div[@class="card_body"]/h4').should('have.text', 'Explore')
        cy.xpath('//p[text()="Click to know more about solvendo.io/india"]').should('have.text', 'Click to know more about solvendo.io/india')
    }
    verifyCaseStudy() {
        cy.contains('Case Studies').should('exist')
        cy.contains('Restructuring Companies').should('exist')
        cy.contains('Full Article ').should('exist')
    }
    verfiyOurVision() {
        cy.contains('Doing business in India is like driving on the streets of India. Just like driving on the streets of India will make you perhaps one of the finest in driving, we believe doing business in India creates the best in enterprise. We, at Solvendo, true to our name, persevere to make this enterprising journey of Indian entrepreneurs easier by solving some of the big problems concerning debt and stress that plague Indian enterprise. We do this through our proprietary data science engines. We welcome you to come chat with us to explore if we can be of any assistance.')
            .should('exist')
        cy.xpath('//i[@class="icon-lg logo-white"]').should('be.visible')
        cy.xpath('//p[text()="Our Vision"]').should('be.visible')
        cy.xpath('//*[@id="root"]/div/div/div[3]/div[3]/div[3]/div[1]/div/img').should('be.visible')
    }
    nextStep() {
        cy.contains('Next Step:').should('exist')
        cy.contains('Your Solvendo Stress Report is ready! ').should('exist')
        cy.contains('View detailed analysis of the stress by clicking on the').should('exist')
        cy.contains('Financial data should ideally be no later than 2 weeks old. For any queries, please').should('exist')
        cy.contains('Blue Card ').should('exist')
    }
    verifyReport() {
        cy.contains('Report Generated').should('exist')
        cy.contains('Detailed analysis of').should('exist')
        //cy.contains('Johnson Watch Company Private Limited').should('exist')
        cy.contains('financial health and a Proposal has been generated by Team Solvendo.').should('exist')
        cy.contains('Stress Level:').should('exist')
        cy.contains('LOW').should('exist')
        cy.contains('HIGH').should('exist')
        cy.contains('View report for detailed analysis').should('exist')
        cy.xpath('//div[@role="progressbar"]').should('exist')
    }
    viewReport() {
        cy.xpath('//a[text()="View Report"]').click({ force: true })
        cy.wait(2000)
        cy.contains('Table of Contents').should('exist')
        cy.contains('Stress Report Summary').click({ force: true })
        cy.contains('Industry Stress').should('exist')
        cy.contains('Industry Stress').should('exist')
        cy.contains('Company Name').should('exist')
        cy.contains('Class of Company').should('exist')
        cy.contains('Company Category').should('exist')
        cy.contains('Company Status').should('exist')
        cy.contains('Company Sub-Category').should('exist')
        cy.contains('Date of Incorporation').should('exist')
        cy.contains('RoC').should('exist')
        cy.contains('Abstract').should('exist')
        cy.go('back')
        cy.contains('Section A - Data Information & Insights').click({ force: true })
        cy.contains('Section A - Data Information & Insights (Part 1)').should('exist')
        cy.go('back')
        cy.contains('Section B - Stress Prediction & Insights').click({ force: true })
        cy.contains('Section B - Stress Prediction & Insights').should('exist')
        cy.go('back')
        cy.contains('Model Analytics').click({ force: true })
        cy.contains('Model Analytics').should('exist')
        cy.go('back')
        cy.contains('Scorecards').click({ force: true })
        cy.contains('Scorecard based on Shri K.V Kamath Committee Report by RBI').should('exist')
        cy.go('back')
        cy.contains('Conclusion').click({ force: true })
        cy.contains('Stress Degree').should('exist')
        cy.contains('RBI Score').should('exist')
        cy.contains('Solvendo Score').should('exist')
        cy.go('back')
        cy.wait(3000)
    }
    connectToBank() {
        cy.wait(2000)
        cy.contains('Connect to my Bank').should('exist')
        cy.contains('Allows you to connect with your bank to ').should('exist')
        cy.contains('attempt to restructure your company/firm based on the report.').should('exist')
        cy.xpath('//i[@class="icon-lg link"]').should('exist')
        cy.xpath('//i[@class="icon-lg link"]').click({ force: true })
        cy.contains(" That's Great!").should('exist')
        cy.xpath('//i[@class="icon close-lg"]').click({ force: true })
    }
    industryStress() {
        cy.contains('Industry Stress').should('exist')
        cy.get('.mb-0 > small').should('exist')
        cy.contains('Stress Level:').should('exist')
        cy.contains('LOW').should('exist')
        cy.contains('HIGH').should('exist')
        cy.xpath('//i[@class="icon-lg link"]').should('exist')
        cy.contains('other industries ').should('exist')
    }
    helpDesk() {
        cy.contains('Help Desk Executive').should('exist')
        cy.contains('Contact us to receive assistance to view the Stress Report for').should('exist')
        cy.contains('Click on Connect Me to schedule a call as per your convenience.').should('exist')
        cy.xpath('//div[@class="badge-ribbon"]').should('be.visible')
        cy.xpath('//a[text()="Connect Me "]').click({ force: true })
        cy.contains('Please select your preferred date and time to').should('exist')
        cy.contains('schedule a call from SolveX.').should('exist')
        cy.xpath('//i[@class="icon close-lg"]').click({ force: true })
    }
    helpDesk2() {
        cy.contains('Help Desk Executive').should('exist')
        cy.contains('Contact us to receive assistance in uploading the financials of').should('exist')
        cy.contains('Click on Connect Me to schedule a call as per your convenience.').should('exist')
        cy.xpath('//div[@class="badge-ribbon"]').should('be.visible')
        cy.xpath('//a[text()="Connect Me "]').click({ force: true })
        cy.contains('Please select your preferred date and time to').should('exist')
        cy.contains('schedule a call from SolveX.').should('exist')
        cy.xpath('//i[@class="icon close-lg"]').click({ force: true })
    }
    likeCard() {
        cy.xpath('//i[@class="icon-lg like"]').should('exist')
        cy.contains('Firms').should('exist')
        cy.contains('Restructured since March 2020, across the world.').should('exist')
    }
    industryCard() {
        cy.contains('INDUSTRY NEWS').should('exist')
        cy.contains('More ').should('exist')
    }
    tour() {
        cy.xpath('//i[@class="icon tour-flag"]').click({ force: true })
        cy.contains('Hi, ').should('exist')
        cy.contains('Let us take you through the Solvendo platform and introduce you to some cool features.').should('exist')
        cy.contains('You may view this tour again by clicking on this icon.').should('exist')
        cy.wait(1000)
        cy.xpath('//i[@class="icon close-lg"]').click({ force: true })
    }
    search() {
        // cy.wait(3000)
        cy.xpath('//i[@class="icon search"]').click({ force: true }).should('be.enabled')

    }
    clickOnNews() {
        // cy.wait(3000)
        cy.get('#news > .icon').click({ force: true })
        //title Verification
        cy.xpath('//span[@class="section-title ml-2"]').should('have.text', 'News')
        cy.url().should('be.equal', 'http://cva-india-test.s3-website.ap-south-1.amazonaws.com/dashboard/debtor')
        //cy.xpath('//span[@class="section-title ml-2"]').click({ force: true })

    }
    clickOnTasks() {

        cy.get('#tasks > .icon').click({ force: true })
        //title Verification
        cy.xpath('//span[@class="section-title ml-2"]').should('have.text', 'Tasks for Solvendo')
        cy.url().should('be.equal', 'http://cva-india-test.s3-website.ap-south-1.amazonaws.com/dashboard/debtor')
       

    }
    clickOnNotifications() {

        // returning false here prevents Cypress from
        //cy.xpath('//i[@class="icon  notifications"]').click({ force: true })
        cy.get('#notifications > div > .icon').click({ force: true })
        cy.xpath('//span[@class="section-title ml-2"]').should('have.text', 'Notifications')
        //cy.xpath('//span[@class="section-title ml-2"]').click({ force: true })

    }
    clickOnMeeting() {
        cy.xpath('//i[@class="icon meeting-room"]').click({ force: true })
        cy.xpath('//span[@class="section-title ml-2"]').should('have.text', 'Meetings')
    }
    clickOnProfile() {
        cy.xpath('//img[@class="profile_icon_dp"]').click({ force: true })
    }
    uploadData() {
        cy.contains('Upload data').should('exist')
        cy.wait(2000)
        cy.contains('Accuracy and relevance of the report depends upon the data you share with us.').should('exist')
        cy.contains('We emphasize that you share as much data with us as possible and ensure that the latest data is no older than 2 weeks from the date of upload.').should('exist')
        cy.contains('Click to upload financial data').should('exist')
        //cy.xpath('//i[@class="icon-lg upload_data_white"]').click({ force: true })
        cy.get('#upload-debtor-data').click({ force: true })
        cy.contains('Upload Data').should('exist')
        cy.contains('(All documents should be at least').should('exist')
        cy.contains('from Financial Year').should('exist')
        cy.contains(' 2016-17 till no older than 2 weeks').should('exist')
        cy.contains('from the date of upload.) ').should('exist')
        cy.get('#dropdown-balanceSheetDate').click({ force: true })
        cy.wait(2000)
        cy.xpath('//div[@class="dd_menu_body"]/a')//selecting year
            .each(($el, index, $list) => {
                var yeard = $el.text()
                //info.singledigitdate
                if (yeard == '2019-20') {
                    cy.wrap($el).click()
                    // $el.click({force:true})
                }
            })
        cy.get('#dropdown-filterBalanceSheet').click({ force: true })
        cy.xpath('//div[@class="dd_menu_body"]/a')//selecting timeperiod
            .each(($el, index, $list) => {
                var timeperiod = $el.text()
                //info.singledigitdate
                if (timeperiod == 'Annual') {
                    cy.wrap($el).click()
                    // $el.click()
                }
            })
        cy.wait(2000)
        cy.get('.third-step-upload-data > input:nth-child(2)').click({ force: true })
        cy.get('.third-step-upload-data > input:nth-child(2)').attachFile('files/image6.jpg')
        cy.wait(10000)
        cy.wait(2000)
        // cy.wait(':nth-child(2) > .col-md-8 > .add_more_col > span > .icon')
        cy.get(':nth-child(2) > .col-md-8 > .add_more_col > span > .icon').click({ force: true })
        cy.get('#dropdown-balanceSheetDate').click({ force: true })
        cy.xpath('//div[@class="dd_menu_body"]/a')//selecting year
            .each(($el, index, $list) => {
                var yeard = $el.text()
                //info.singledigitdate
                if (yeard == '2018-19') {
                    cy.wrap($el).click()
                    //$el.click()
                }
            })
        cy.get('#dropdown-filterBalanceSheet').click({ force: true })
        cy.xpath('//div[@class="dd_menu_body"]/a')//selecting timeperiod
            .each(($el, index, $list) => {
                var timeperiod = $el.text()
                //info.singledigitdate
                if (timeperiod == 'Q1') {
                    cy.wrap($el).click()
                    // $el.click()
                }
            })
        cy.wait(3000)
        cy.get('#uploadFileWrap > div:nth-child(2) > div.col-md-8 > div.right_input_col > div.input_col.third-step-upload-data > input[type=file]').click({ force: true })
        cy.get('#uploadFileWrap > div:nth-child(2) > div.col-md-8 > div.right_input_col > div.input_col.third-step-upload-data > input[type=file]').attachFile('files/image6.jpg')
        cy.wait(4000)
        //cy.get('.third-step-upload-data > .btn').click({force:true})        
        cy.wait(3000)
        //cash flow
        cy.get('#dropdown-cashflowDate').click({ force: true })
        cy.xpath('//div[@class="dd_menu_body"]/a')//selecting year
            .each(($el, index, $list) => {
                var yeard = $el.text()
                //info.singledigitdate
                if (yeard == '2018-19') {
                    cy.wrap($el).click({ force: true })
                    //  $el.click()
                }
            })
        cy.wait(3000)
        cy.get('#dropdown-cashFlowFilter').click({ force: true })
        cy.xpath('//div[@class="dd_menu_body"]/a')//selecting timeperiod
            .each(($el, index, $list) => {
                var timeperiod = $el.text()
                //info.singledigitdate
                if (timeperiod == 'Annual') {
                    cy.wrap($el).click({ force: true })
                    //$el.click()
                }
            })
        cy.wait(3000)
        cy.get('#uploadFileWrap > div:nth-child(3) > div.col-md-8 > div.right_input_col > div:nth-child(3) > input[type=file]').click({ force: true })
        cy.get('#uploadFileWrap > div:nth-child(3) > div.col-md-8 > div.right_input_col > div:nth-child(3) > input[type=file]').attachFile('files/image6.jpg')
            .attachFile('files/image6.jpg')
        cy.wait(4000)
        cy.get('#dropdown-plDate').click()
        cy.xpath('//div[@class="dd_menu_body"]/a')//selecting year
            .each(($el, index, $list) => {
                var yeard = $el.text()
                //info.singledigitdate
                if (yeard == '2018-19') {
                    cy.wrap($el).click({ force: true })
                    // $el.click()
                }
            })
        cy.wait(2000)
        cy.get('#dropdown-plFilter').click({ force: true })
        cy.xpath('//div[@class="dd_menu_body"]/a')//selecting timeperiod
            .each(($el, index, $list) => {
                var timeperiod = $el.text()
                //info.singledigitdate
                if (timeperiod == ' Latest') {
                    cy.wrap($el).click({ force: true })
                    // $el.click()
                }
            })
        cy.wait(3000)
        cy.get('#uploadFileWrap > div:nth-child(4) > div.col-md-8 > div.right_input_col.profit_loss_col > div:nth-child(3) > input[type=file]').click({ force: true })
        cy.get('#uploadFileWrap > div:nth-child(4) > div.col-md-8 > div.right_input_col.profit_loss_col > div:nth-child(3) > input[type=file]').attachFile('files/image5.jpg')
        cy.wait(4000)
        //  cy.xpath('//button[text()="Save"]').click({force:true})
        cy.xpath('//button[text()="Upload"]').click({ force: true })
        cy.contains('Confirm Upload').should('exist')
        cy.contains('Kindly confirm that you are aware and accept that the accuracy and relevance of the report depends upon the data you share with Solvendo. Change in data affects the accuracy of the report.Please confirm that you have shared the following files by checking the name, type, year, relevance and accuracy.').should('exist')
        cy.xpath('//button[text()="Confirm"]').click({ force: true })
        cy.wait(2000)
        cy.xpath('//button[@class="reactour__close sc-bxivhb eTpeTG sc-bdVaJa cYQqRL"]').click({ force: true })
    }
    nextStep2() {
        cy.contains('Next Step:').should('exist')
        cy.contains('Upload ').should('exist')
        cy.contains('latest').should('exist')
        cy.contains(' financial documents ').should('exist')
        cy.contains(' of last 5 years or that which is available by clicking the').should('exist')
        cy.contains('Blue Card ').should('exist')
        cy.contains('Which documents are required?').should('exist')
        cy.contains('Why are these documents required?').should('exist')
        cy.xpath('//button[text()="Which documents are required?"]').click({ force: true })
        cy.contains('Financial Documents').should('exist')
        cy.contains('Supported file formats .pdf, .xls, .xlsx, .odt, .txt, .doc, .docx, .jpg, .png and .rtf').should('exist')
        cy.contains('Balance sheets').should('exist')
        cy.contains('Cash flow statements').should('exist')
        cy.contains('Profit & loss statements').should('exist')
        cy.xpath('//button[text()="Got It"]').click({ force: true })
        cy.xpath('//button[text()="Why are these documents required?"]').click({ force: true })
        cy.contains('Why are these documents required?').should('exist')
        cy.xpath('//i[@class="icon close-lg"]').click({ force: true })
    }
    contactUsNextStep() {
        cy.xpath('//a[text()="Contact Us."]').click({ force: true })
        cy.contains(' Sure,').should('exist')
        cy.contains('Please select your preferred date and time to').should('exist')
        cy.contains('schedule a call from SolveX.').should('exist')
    }

    scheduleDate() {

        cy.xpath("//i[@class='icon arrow-down']").click({ force: true })

        //select Month& Year
        for (let i = 0; i < buttonpress + 1; i++) {//+1
            cy.xpath("//html/body/div[4]/div[3]/div/div/div[1]/div[1]/button[2]/span[1]").click({ force: true })
        }

        cy.xpath('//div[@class="MuiPickersSlideTransition-transitionContainer MuiPickersCalendar-transitionContainer"]/div/div/div')
            .each(($el, index, $list) => {
                var dateName = $el.text()
                if (dateName == datevalue) {

                    // cy.wrap($el).click()
                    $el.click()
                }

            })
    }
    selectTime() {
        cy.get('#time').click()
        cy.xpath('//div[@class="dd_body"]/a')
            .each(($el, index, $list) => {
                var seltime = $el.attr('data-time')
                cy.log(seltime)
                if (seltime == info1.time) {
                    expect(seltime).to.equal(info1.time)
                    cy.wrap($el).click({ force: true })


                }
            })

    }
    selectTimeNotAvailable() {
        cy.get('#time').click()
        cy.xpath('//div[@class="dd_body"]/a')
            .each(($el, index, $list) => {
                var seltime = $el.attr('data-time')
                cy.log(seltime)
                if (seltime == info1.time) {
                    expect(seltime).to.not.equal(info1.wrongtime)
                    cy.log('Please select time after 11:00 and before 18:00')

                    // cy.get('.button_wrap > .btn').click({force:true})

                }
            })

    }
    currentDateandTime() {
        var today = new Date();
        var currentdate = today.getDate()
        cy.log(currentdate)

        var time = today.getHours() + " to " + (today.getHours() + 1);

        var timemsg = (today.getHours() + 4);
        //  cy.log(time)
        cy.get('.MuiIconButton-label > .icon').click()
        cy.xpath('//div[@class="MuiPickersBasePicker-pickerView"]/div/div/div/div')
            .each(($el, index, $list) => {
                var dateName = $el.text()
                if (dateName == currentdate) {

                    //  cy.wrap($el).click()
                    $el.click({ force: true })
                }
            })
        //selecting time
        cy.get('#time').click({ force: true })
        cy.xpath('//div[@class="dd_body"]/a')
            .each(($el, index, $list) => {
                var seltime = $el.attr('data-time')
                // cy.log(seltime)
                if (seltime != time) {
                    cy.log('You can Schedule a call after 4 hrs but before 18:00pm otherwise select another Day')
                    return false;

                }
                else {

                    cy.wrap($el).click({ force: true })
                    cy.xpath('//button[text()="Confirm"]').click()
                }
            })
    }

    clickOnNoted() {
        cy.contains('You have scheduled a call from')
        cy.contains('SolveX on ')
        cy.get('#noted').click({ force: true })
        cy.wait(1000)
        cy.url().should('eq', 'http://cva-india-test.s3-website.ap-south-1.amazonaws.com/dashboard/debtor#!')
    }

    notedDateAndTime() {

        var datesuffix;


        if (datevalue >= 11 && datevalue <= 13) {
            datesuffix = "th";
        } else {
            switch (datevalue % 10) {
                case 1:
                    datesuffix = "st";
                    break;

                case 2:
                    datesuffix = "nd";
                    break;

                case 3:
                    datesuffix = "rd";
                    break;

                default:
                    datesuffix = "th";
            }
        }

        // var demodate = info1.date;
        //  var demodate=Dates.substring(0,2);
        var demomonth = Dates.substring(3, 18)
        var demotime = info1.time;



        //cy.xpath("//div[@role='dialog']//strong[1]")
        cy.xpath('//span[@id="callDate"]')


            .each(($el, index, $list) => {

                var dt = $el.text()

                // expect(' SolveX on  ' + demodate + 'th ' + info1.month + ' ' + info1.Year).to.equal(dt)
                expect(datevalue + datesuffix + ' ' + demomonth).to.equal(dt)

            })

        var tm = cy.xpath("//div[@role='dialog']//strong[2]")
            .each(($el, index, $list) => {
                var tm = $el.text()
                expect(demotime).to.equal(tm)
                cy.log(tm)
            })
    }

    disabledButton() {
        cy.xpath('//button[text()="Confirm"]').should('be.disabled')
    }
    confirmButton() {
        cy.wait(2000)
        cy.xpath('//*[@id="confirm"]').click({ force: true })
    }

    resheduleCall() {

        cy.xpath('//p[text()="Reschedule it"]').click({ force: true })
        cy.contains(' Sure,').should('exist')
        cy.contains('Please select your preferred date and time to').should('exist')
        cy.contains('schedule a call from SolveX.').should('exist')
    }
    closeButton() {
        cy.xpath('//i[@class="icon close-lg"]').click({ force: true })
    }
}
export default DebtorDashboard