///<reference types="cypress-xpath" />
import info from '../../fixtures/logindata.json'
import Login from '../POM/Login'
import DebtorTourFlow from '../POM/DebtorTourFlow';
describe('Tour', function () {
    const sn = new Login();
    const dbt = new DebtorTourFlow();

    it('CVA_A_TC-30:  Verify that on click of tour icon debtor is able to open tour window/screen', function () {
        sn.visit()
        sn.fillEmail(info.email)
        sn.fillPassward(info.password)
        sn.submit()
        dbt.tour()
        dbt.verifyTexts()
    })

    it('CVA_A_TC-30-01:  Verify that on click of take a tour button debtor is able to get explore solvendo window/screen', function () {
        sn.visit()
        sn.fillEmail(info.email)
        sn.fillPassward(info.password)
        sn.submit()
        dbt.tour()
        dbt.takeTourButton()
        dbt.expolre()
    })

    it('CVA_A_TC-30-02:  Verify that on click of next in explore window/screen debtor is able to get next step window/screen', function () {

        dbt.nextButton()
        dbt.nextStep()
    })
    it('CVA_A_TC-30-03:  Verify that on click of next in next step window/screen debtor is able to get view report window/screen', function () {

        dbt.nextButton()
        dbt.viewReport()
    })
    it('CVA_A_TC-30-04:  Verify that on click of next in view reprt window/screen debtor is able to get industry news window/screen', function () {

        dbt.nextButton()
        dbt.industryNews()
    })
    it('CVA_A_TC-30-05:  Verify that on click of next in industry news window/screen debtor is able to get case studies window/screen', function () {

        dbt.nextButton()
        dbt.caseStudies()
    })
    it('CVA_A_TC-30-06:  Verify that on click of next in case studies window/screen debtor is able to get connect to my bank window/screen', function () {

        dbt.nextButton()
        dbt.connectToMyBank()
        dbt.verifyConnectToBank()
    })
    it('CVA_A_TC-30-07:  Verify that on click of next in connect to bank window/screen debtor is able to get industry stress window/screen', function () {

        dbt.nextButton()
        dbt.industryStress()
    })
    it('CVA_A_TC-30-08:  Verify that on click of next in industry stress window/screen debtor is able to get help desk executive window/screen', function () {

        dbt.nextButton()
        dbt.helpDesk()
    })
    it('CVA_A_TC-30-09:  Verify that on click of next in help desk executive window/screen debtor is able to get our vision window/screen', function () {

        dbt.nextButton()
        dbt.vision()
    })
    it('CVA_A_TC-30-10:  Verify that on click of close icon debtor is able to close tour window/screen', function () {
        sn.visit()
        sn.fillEmail(info.email)
        sn.fillPassward(info.password)
        sn.submit()
        dbt.tour()
        dbt.closeButton()
    })
    it('CVA_A_TC-30-11:  Verify that on click of close icon in explore window/screen debtor is able to close explore solvendo window/screen', function () {
        sn.visit()
        sn.fillEmail(info.email)
        sn.fillPassward(info.password)
        sn.submit()
        dbt.tour()
        dbt.takeTourButton()
        dbt.expolre()
        dbt.closeExplore()
    })
    it('CVA_A_TC-30-12:  Verify that on click of close icon in next step window/screen debtor is able to redirect to the debtor dashboard', function () {
        sn.visit()
        sn.fillEmail(info.email)
        sn.fillPassward(info.password)
        sn.submit()
        dbt.tour()
        dbt.takeTourButton()
        dbt.expolre()
        dbt.nextButton()
        dbt.nextStep()
        dbt.closeExplore()
    })

    it('CVA_A_TC-30-13:  Verify that on click of close icon in view report window/screen debtor is able to redirect to the debtor dashboard', function () {
        sn.visit()
        sn.fillEmail(info.email)
        sn.fillPassward(info.password)
        sn.submit()
        dbt.tour()
        dbt.takeTourButton()
        dbt.nextButton()
        dbt.nextStep()
        dbt.nextButton()
        dbt.viewReport()
        dbt.closeExplore()
    })
    it('CVA_A_TC-30-14:  Verify that on click of close icon in industry news window/screen debtor is able to redirect to the debtor dashboard', function () {
        sn.visit()
        sn.fillEmail(info.email)
        sn.fillPassward(info.password)
        sn.submit()
        dbt.tour()
        dbt.takeTourButton()
        dbt.nextButton()
        dbt.nextStep()
        dbt.nextButton()
        dbt.viewReport()
        dbt.nextButton()
        dbt.industryNews()
        dbt.closeExplore()
    })
    it('CVA_A_TC-30-15:  Verify that on click of close icon in case studies window/screen debtor is able to redirect to the debtor dashboard', function () {
        sn.visit()
        sn.fillEmail(info.email)
        sn.fillPassward(info.password)
        sn.submit()
        dbt.tour()
        dbt.takeTourButton()
        dbt.nextButton()
        dbt.nextStep()
        dbt.nextButton()
        dbt.viewReport()
        dbt.nextButton()
        dbt.industryNews()
        dbt.nextButton()
        dbt.caseStudies()
        dbt.closeExplore()
    })
    it('CVA_A_TC-30-16:  Verify that on click of close icon in connect to my bank window/screen debtor is able to redirect to the debtor dashboard', function () {
        sn.visit()
        sn.fillEmail(info.email)
        sn.fillPassward(info.password)
        sn.submit()
        dbt.tour()
        dbt.takeTourButton()
        dbt.nextButton()
        dbt.nextStep()
        dbt.nextButton()
        dbt.viewReport()
        dbt.nextButton()
        dbt.industryNews()
        dbt.nextButton()
        dbt.caseStudies()
        dbt.nextButton()
        dbt.connectToMyBank()
        dbt.verifyConnectToBank()
        dbt.closeExplore()
    })
    it('CVA_A_TC-30-17:  Verify that on click of close icon in industry stress window/screen debtor is able to redirect to the debtor dashboard', function () {
        sn.visit()
        sn.fillEmail(info.email)
        sn.fillPassward(info.password)
        sn.submit()
        dbt.tour()
        dbt.takeTourButton()
        dbt.nextButton()
        dbt.nextStep()
        dbt.nextButton()
        dbt.viewReport()
        dbt.nextButton()
        dbt.industryNews()
        dbt.nextButton()
        dbt.caseStudies()
        dbt.nextButton()
        dbt.connectToMyBank()
        dbt.nextButton()
        dbt.industryStress()
        dbt.closeExplore()
    })
    it('CVA_A_TC-30-18:  Verify that on click of close icon in help desk executive window/screen debtor is able to redirect to the debtor dashboard', function () {
        sn.visit()
        sn.fillEmail(info.email)
        sn.fillPassward(info.password)
        sn.submit()
        dbt.tour()
        dbt.takeTourButton()
        dbt.nextButton()
        dbt.nextStep()
        dbt.nextButton()
        dbt.viewReport()
        dbt.nextButton()
        dbt.industryNews()
        dbt.nextButton()
        dbt.caseStudies()
        dbt.nextButton()
        dbt.connectToMyBank()
        dbt.nextButton()
        dbt.industryStress()
        dbt.nextButton()
        dbt.helpDesk()
        dbt.closeExplore()
    })
    it('CVA_A_TC-30-19:  Verify that on click of close icon in our vision window/screen debtor is able to redirect to the debtor dashboard', function () {
        sn.visit()
        sn.fillEmail(info.email)
        sn.fillPassward(info.password)
        sn.submit()
        dbt.tour()
        dbt.takeTourButton()
        dbt.nextButton()
        dbt.nextStep()
        dbt.nextButton()
        dbt.viewReport()
        dbt.nextButton()
        dbt.industryNews()
        dbt.nextButton()
        dbt.caseStudies()
        dbt.nextButton()
        dbt.connectToMyBank()
        dbt.nextButton()
        dbt.industryStress()
        dbt.nextButton()
        dbt.helpDesk()
        dbt.nextButton()
        dbt.vision()
        dbt.closeExplore()
    })
    it('CVA_A_TC-30-20:  Verify that on click of finish in  our vision window/screen debtor is able to redirect to the debtor dashboard', function () {
        sn.visit()
        sn.fillEmail(info.email)
        sn.fillPassward(info.password)
        sn.submit()
        dbt.tour()
        dbt.takeTourButton()
        dbt.nextButton()
        dbt.nextStep()
        dbt.nextButton()
        dbt.viewReport()
        dbt.nextButton()
        dbt.industryNews()
        dbt.nextButton()
        dbt.caseStudies()
        dbt.nextButton()
        dbt.connectToMyBank()
        dbt.nextButton()
        dbt.industryStress()
        dbt.nextButton()
        dbt.helpDesk()
        dbt.nextButton()
        dbt.vision()
        dbt.finish()
    })
})